### ISSUE TITLE
rp-halに対して into_push_pull_output 時に出力の初期値を設定する版を追加してリセットピンの初期値が確実にHとなるように対応

### ISSUE THREAD

**Issue by ciniml** [ciniml/rust-dap#40]
現状だと一瞬 `L` になるのが避けられないので、rp-halをforkして対応可能かを検討し、対応できた場合はrp-halにPRを投げる

https://github.com/ciniml/rust-dap/pull/35#discussion_r923600092

**Comment by 9names** [comment]
Setting the initial state of an output pin was added in https://github.com/rp-rs/rp-hal/pull/452 so this should be fixed in the next HAL release.
```rust
pin.into_push_pull_output();
```
becomes
```rust
pin.into_push_pull_output_in_state(PinState::High);
```
or
```rust
pin.into_push_pull_output_in_state(PinState::Low);
```
