### ISSUE TITLE
rpi_pico 用ビルドがデフォルトで通りません

### ISSUE THREAD

**Issue by elfmimi** [ciniml/rust-dap#41]
`cd boards/rpi_pico; cargo build`
とした時に ビルドが成功して欲しい、というのが普通だと思うのですが、
`--features=swd` か `--features=jtag` のいずれかを指定しないとビルドが成功しません。

Cargo.toml に、 `default = ["swd"]` を追加することは出来ないでしょうか？
ただしこの場合 jtag を有効にしてビルドするには、
`--features=jtag --no-default-features` とすることになります。

※ pio で jtag も出来るようにして両立するようにするのが一番いいのですけども。

@tnishinaga

**Comment by ciniml** [comment]
そういやそれ直そうと思ってわすれてました…

しばらくはデフォルトSWDにして、JTAG向け含めてビルド手順記載にしようと思います。

**Comment by ciniml** [comment]
#42 マージしたのでcloseします。
