### ISSUE TITLE
main ブランチが正しく動きません

### ISSUE THREAD

**Issue by elfmimi** [ciniml/rust-dap#44]
~調査中です。~
openocd や pyocd の場合、コマンドが詰まってタイムアウトしてしまうようです。→ panic で落ちています。

[8d623a92](https://github.com/ciniml/rust-dap/commit/8d623a9250757a248691046ad320becc1671f3f6) は動きます。
[4f4effba ](https://github.com/ciniml/rust-dap/commit/4f4effbafba16f9897b84e57fcd1241390950751) 以降動かないようです。

**Comment by elfmimi** [comment]
この修正が抜け落ちてしまっている regression でした。
https://github.com/ciniml/rust-dap/pull/12 swd_sequence() の誤動作の修正
https://github.com/ciniml/rust-dap/commit/593c30b906353a21bb3370c09e2cd88158ed4d97 Fix swd_sequence() malfunction

**Comment by ciniml** [comment]
普通に手元だとSWDで書き込みできてたけど、デバッグすると落ちる感じですかね。

**Comment by elfmimi** [comment]
probe-rs / probe-run は、 swd_sequence() の代わりに swj_sequence() で済ませているので問題が起きないということのようです。

**Comment by ciniml** [comment]
あーなるほど。ありがとうございます。

今日帰ってきたら修正します。
