### ISSUE TITLE
DAP_Transferコマンドの処理に不備があります

### ISSUE THREAD

**Issue by elfmimi** [ciniml/rust-dap#5]
CMSIS_5 の DAP.c で言うと [852行目](https://github.com/ARM-software/CMSIS_5/blob/7bb14d86eaa4eff757672705296bf0fe563007e3/CMSIS/DAP/Firmware/Source/DAP.c#L852) に対応する部分が抜けています。
```C
        post_read = 0U;
```
rust-dap のソースでは `fn swd_transfer<SwdIo>()` の [この辺り](https://github.com/ciniml/rust-dap/blob/3eadd09dfbafb68a60968494a078409309ecbc37/src/cmsis_dap.rs#L669-L680) です。

https://github.com/ciniml/rust-dap/blob/3eadd09dfbafb68a60968494a078409309ecbc37/src/cmsis_dap.rs#L669-L680

**Comment by ciniml** [comment]
おっ、ありがとございます。(UARTの実装終わったら確認します。)

これでもOpenOCDは動いてしまうのか…

**Comment by ciniml** [comment]
修正をマージしました。ありがとうございます。
