### ISSUE TITLE
Windows+OpenOCDで動作しない

### ISSUE THREAD

**Issue by ciniml** [ciniml/rust-dap#7]
https://github.com/ciniml/rust-dap/issues/2#issuecomment-1007911113

そういえばWCIDとComposite Deviceの関係で、WinUSB/libusbあたりでうまく扱えないみたいな現象を見た気がするので再確認する。 (Composite Deviceのうち、片方だけがWinUSB管理下だと動かないような感じ)

**Comment by elfmimi** [comment]
こちらですが qmk_driver_installer (＝ほぼ zadig) でインストールしたドライバのレジストリ設定が残っていて
悪さをしていたのではないかという予想なのですが、再現性のある完全なシナリオは分かっていません。

お騒がせしてしまってあれなのですが、一晩経ったらいつの間にか動くようになった、
という形で、今現在は現象が見られなくなっています。

**Comment by ciniml** [comment]
とりあえず手元の環境では、現在のmainのHEAD (https://github.com/ciniml/rust-dap/commit/5518afbd75bd1a0de302f0042d9fd63a7984a56e) でWindows上のOpenOCDで接続してプログラムのダウンロード、リセット、実行、停止ができるのを確認しました。

**Comment by ciniml** [comment]
とりあえず大丈夫そうなのでclose 問題があったらまた別issueで対応
