### ISSUE TITLE
SWDの通信のPIOによる高速化検討

### ISSUE THREAD

**Issue by ciniml** [ciniml/rust-dap#8]
PIO使ったらbit-bangでCPU使うより速くなるんじゃないの？という気がするので、PIO実装できるか検討する。

RustからのPIOの制御は `pio-rs` 使えばできる模様。

https://github.com/rp-rs/pio-rs

あとそれとは別にPIOに処理をオフロードできるようにしたとしてもCMSIS-DAPのコマンド処理がブロッキングだと意味が無いので、バッファリングしてコマンド受信、レスポンス返信、SWDトランザクション実行を並行して実行できるようにする。

Core1を使っていないのでPIOではなくそちらで実行という手もある。 (が、RTICがSMPをサポートしてるかはアヤシイ)

**Comment by elfmimi** [comment]
作業中ですがそこそこの進展があったので共有しおきます。\
https://github.com/elfmimi/rust-dap/tree/pio-wip

最終的には、 bitbang のように rust-dap クレートの側に移すと思います。

**Comment by ciniml** [comment]
なるほど。 `rp2` 系チップ固有実装になると思うので、 `rust-dap ` じゃなくて rp2040クレート もしくは rp2クレートに入れるのがよさそうですね。

XIAO RP2040とRaspberry Pi Picoの共通項抜き出すのやらないとですね…

**Comment by elfmimi** [comment]
だいぶ想定した形に近づきました。
https://github.com/elfmimi/rust-dap/tree/pio-almost-done

**Comment by ciniml** [comment]
おっ、よさげですね。

RP2040の共通化のやつ、mainにマージしてしまっても大丈夫ですかね？

たぶん `MySwdIoSet` とかコメントアウトしたりしてるところ要らなくなって、pio.rsを `rustdap-rs-rp2040` に移動すると、 XIAO RP2040以外でも使いやすくなるはず…

**Comment by elfmimi** [comment]
> RP2040の共通化のやつ、mainにマージしてしまっても大丈夫ですかね？

もちろんです。どんどん進めてもらって大丈夫です。

**Comment by elfmimi** [comment]
がっちゃんこん、とくっつけてみました。
[https://github.com/elfmimi/rust-dap/tree/rp2040-pio](https://github.com/elfmimi/rust-dap/tree/9b46c3a5a33a1d0fa030c45024fcbff511d60b84)

**Comment by ciniml** [comment]
もう動いてる感じですか？　bitbangに比べてパフォーマンス改善してるとうれしいですが。

**Comment by elfmimi** [comment]
コンパイル出来れば動くはず！
かなり安定側に振っているつもりですがbitbangよりは段違いで速いと思います。

**Comment by elfmimi** [comment]
一つの方向性ということで SwdIoSet まわりを出来る限り整理してみました。どうでしょう？
[https://github.com/elfmimi/rust-dap/tree/rp2040-pio](https://github.com/elfmimi/rust-dap/tree/7555bfe69406abb0d7d56686162a2fa272828467)
[前回との差分](https://github.com/elfmimi/rust-dap/compare/9b46c3a5a33a1d0fa030c45024fcbff511d60b84..7555bfe69406abb0d7d56686162a2fa272828467)

**Comment by ciniml** [comment]
よさげですね。切り替えるfeatureを `bitbang` にするのか `pio` にするのかちょっと考えましたが、PIO動き始めたらPIO使わない理由はないので、ご提案通り `bitbang` featureで切り替えるのでよさそうですね。

**Comment by elfmimi** [comment]
[PRと5日前のコメントのrevとの差分](https://github.com/elfmimi/rust-dap/compare/7555bfe69406abb0d7d56686162a2fa272828467..f5255f21f4194dca0c033406328c2fa241f13d20)
ピン配置は変更していません。
